apiVersion: v1
kind: Service
metadata:
  name: {{ include "upload.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "upload.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.upload.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "upload.selectorLabels" . | nindent 4 }}
